### ISSUE TITLE
SignUp form causes error when submitting new user

### ISSUE THREAD

**Issue by SteveTeece** [TheUnit-Grafton/UnitAdminApplication#33]
When creating a new user via the SignUp control, on submit, an error is generated advising there is no Two Factor Authentication provider of type <T> called Default available.

The user is still correctly written to the database.

**Comment by SteveTeece** [comment]
Error from Developer Tools:
```
[2020-09-23T03:03:16.784Z] Error: System.NotSupportedException: No IUserTwoFactorTokenProvider<TUser> named 'Default' is registered.
   at UnitAdmin.Areas.Identity.RevalidatingIdentityAuthenticationStateProvider`1.GetUrl(TUser user, String id, String baseuri, String path) in C:\SourceCode\TheUnit\UnitAdminApplication\UnitAdmin\Areas\Identity\RevalidatingIdentityAuthenticationStateProvider.cs:line 350
   at UnitAdmin.Areas.Identity.RevalidatingIdentityAuthenticationStateProvider`1.GetUrl(TUser user, String id, String baseuri, String path) in C:\SourceCode\TheUnit\UnitAdminApplication\UnitAdmin\Areas\Identity\RevalidatingIdentityAuthenticationStateProvider.cs:line 362
   at UnitAdmin.Areas.Identity.Pages.Account.SignUp.ValidSubmit() in C:\SourceCode\TheUnit\UnitAdminApplication\UnitAdmin\Areas\Identity\Pages\Account\SignUp.razor.cs:line 59
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.Forms.EditForm.HandleSubmitAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

Modify startup.cs to include default Identity Tokens per https://www.codegrepper.com/code-examples/csharp/No+IUserTwoFactorTokenProvider%3CTUser%3E+named+%27Default%27+is+registered.%27 and error does not occur, but user is also returned to the home page with user not logged in.

Manual login works as expected, but the Signup button should redirect to the home page with the user logged in.

**Comment by SteveTeece** [comment]
It is not intended for people to be able to Self Register for this system.

An Authorised user will need to manually create accounts and allocate roles for any new users, so this functionality is not really required for this release.

This bug will not be fixed.
