### ISSUE TITLE
Unhandled Exception when editing Activities from main screen

### ISSUE THREAD

**Issue by SteveTeece** [TheUnit-Grafton/UnitAdminApplication#40]
**Describe the bug**
Trying to edit a current activity from the Home screen causes Unhandled Exception Error.

**To Reproduce**
1. Sign In
2. Click "Edit" button against one of the activities
3. Error reported:

> blazor.server.js:19 [2020-08-12T23:48:41.570Z] Error: System.InvalidOperationException: EditForm requires a Model parameter, or an EditContext parameter, but not both.
>    at Microsoft.AspNetCore.Components.Forms.EditForm.OnParametersSet()
>    at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
>    at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()

**Expected behavior**
Edit Activity screen should appear and be populated with correct data

**Comment by SteveTeece** [comment]
Fixed in PR#42
