### ISSUE TITLE
Signin causes server disconnection

### ISSUE THREAD

**Issue by SteveTeece** [TheUnit-Grafton/UnitAdminApplication#43]
**Describe the bug**
On sign in with correct username and password, system drops connection to server and wants to reload.  Issue only appears to occur on the production server.

**To Reproduce**
1. Go to 'https://admin.theunit.club'
2. Click on 'Signin'
3. Enter a valid Username and Pasword
4. Click login
5. Yellow reload bar appears at bottom of browser indicating SignalR disconnect.

**Expected behavior**
Successful login should redirect user to Home page

**Comment by SteveTeece** [comment]
Unable to duplicate error on development system with development database.
Change dev ConnectionString to connect to live database for testing. Error occurs.

Developer Tools output from error:
MySql.Data.MySqlClient.MySqlException (0x80004005): Unknown column 'a.Position' in 'field list'
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Unknown column 'a.Position' in 'field list'
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 774
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 49
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 130
   at MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 391
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\CommandExecutor.cs:line 62
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.UserManager`1.FindByNameAsync(String userName)
   at UnitAdmin.Areas.Identity.RevalidatingIdentityAuthenticationStateProvider`1.FindByNameAsync(String username) in C:\SourceCode\TheUnit\UnitAdminApplication\UnitAdmin\Areas\Identity\RevalidatingIdentityAuthenticationStateProvider.cs:line 277
   at UnitAdmin.Areas.Identity.RevalidatingIdentityAuthenticationStateProvider`1.FindByNameAsync(String username) in C:\SourceCode\TheUnit\UnitAdminApplication\UnitAdmin\Areas\Identity\RevalidatingIdentityAuthenticationStateProvider.cs:line 290
   at UnitAdmin.Areas.Identity.Pages.Account.SignIn.ValidateUser() in C:\SourceCode\TheUnit\UnitAdminApplication\UnitAdmin\Areas\Identity\Pages\Account\SignIn.razor.cs:line 33
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.Forms.EditForm.HandleSubmitAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)

**Comment by SteveTeece** [comment]
Run database migration on production server to add missing fields. Tested OK.
Fixes #43
